version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env.test
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      - db
      - redis

volumes:
  pgdata: