version: '3'

services:
  users-db:
    image: postgres
    env_file:
      - .env.dev
    networks:
      - chack-check-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  users-redis:
    image: redis
    networks:
      - chack-check-network
  users-mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - chack-check-network
  users-migrations:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./src/:/src/
    command: alembic upgrade head
    networks:
      - chack-check-network
    env_file:
      - .env.dev
    depends_on:
      - users-db
  users-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      -  ./src/:/src/
    command: uvicorn infrastructure.api.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    env_file:
      - .env.dev
    ports:
      - 8000:8000
      - 9090:9090
    depends_on:
      - users-db
      - users-redis
      - users-mailhog
    networks:
      - chack-check-network

networks:
  chack-check-network:
    name: chack-check-network
    external: true

volumes:
  pgdata:
