version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./app:/src/app
      - ./templates:/src/templates
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env.dev
    ports:
      - 8000:8000
      - 9090:9090
    depends_on:
      - db
      - redis
      - mailhog

volumes:
  pgdata: