version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env.test
  redis:
    image: redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  migrations:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    command: alembic upgrade head
    env_file:
      - .env.test
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      - db
      - migrations
      - redis
      - mailhog