apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service-mailhog
  template:
    metadata:
      labels:
        app: users-service-mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 1025
              name: mail
            - containerPort: 8025
              name: interface