apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chack-mailhog-service-ingress
  labels:
    app: users-service-mailhog
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - mailhog.diffaction.com
    secretName: letsencrypt
  rules:
  - host: mailhog.diffaction.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailhog-service
            port:
              number: 8025