apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chack-mailhog-service-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: mailhog.chack-check.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailhog-service
            port:
              number: 8025