apiVersion: apps/v1
kind: Deployment
metadata:
  name: chack-users-service-deployment
  labels:
    app: chack-users-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chack-users-service
  template:
    metadata:
      labels:
        app: chack-users-service
    spec:
      containers:
        - name: chack-users-service
          image: artemowkin/chack-users-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: chack-users-service-config
        - name: postgresdb
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-secret-credentials
          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
