from domain.exceptions import BaseDomainException


class BaseUserException(BaseDomainException): ...


class IncorrectPhoneNumber(BaseUserException): ...


class IncorrectEmail(BaseUserException): ...


class SearchUserIncorrectParameters(BaseUserException): ...


class UserNotFound(BaseUserException): ...


class IncorrectPasswordException(BaseUserException): ...


class UserAlreadyExists(BaseUserException): ...
