from infrastructure.exceptions import BaseInfrastructureException


class BaseRedisException(BaseInfrastructureException): ...


class VerificationAttemptsExpired(BaseRedisException): ...


class IncorrectVerificationCode(BaseRedisException): ...


class IncorrectAuthenticationSession(BaseRedisException): ...
