apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diffaction-users-service-ingress
  labels:
    app: diffaction-users-service
  annotations:
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - stage.diffaction.com
    secretName: users-tls
  rules:
  - host: stage.diffaction.com
    http:
      paths:
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: diffaction-users-service
            port:
              number: 8000