apiVersion: v1
kind: Service
metadata:
  name: chack-users-service
spec:
  selector:
    app: chack-users-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: web
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc