FROM python:3.11

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /src

RUN pip install -U poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock /src/

RUN poetry install --with lint --no-interaction --no-ansi

COPY src/ /src/

ENV MYPATH=/src/

ENTRYPOINT [ "/bin/sh", "-c", "flake8 --ignore=E501 . --exclude=protobuf" ]
