FROM python:3.11

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /src

RUN pip install -U poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock /src/

RUN poetry install --with test --no-interaction --no-ansi

COPY alembic.ini /src/
COPY app/ /src/app
COPY alembic/ /src/alembic
COPY templates/ /src/templates
COPY tests /src/tests