from domain.exceptions import BaseDomainException


class BaseSessionException(BaseDomainException): ...


class IncorrectTokenException(BaseSessionException): ...


class NoSessionsToRefreshException(BaseSessionException): ...


class IncorrectAuthData(BaseSessionException): ...
