# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\nprotousers\"\xa8\x02\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x07 \x01(\t\x12\x10\n\x08\x61\x63tivity\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x17\n\x0f\x65mail_confirmed\x18\n \x01(\x08\x12\x17\n\x0fphone_confirmed\x18\x0b \x01(\x08\x12\x11\n\tlast_seen\x18\x0c \x01(\t\x12\x1b\n\x13original_avatar_url\x18\r \x01(\t\x12\x1c\n\x14\x63onverted_avatar_url\x18\x0e \x01(\t\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\",\n\x18GetUserByUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"&\n\x15GetUserByTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t2\xa3\x03\n\x05Users\x12I\n\x0bGetUserById\x12\x1e.protousers.GetUserByIdRequest\x1a\x18.protousers.UserResponse\"\x00\x12U\n\x11GetUserByUsername\x12$.protousers.GetUserByUsernameRequest\x1a\x18.protousers.UserResponse\"\x00\x12O\n\x0eGetUserByEmail\x12!.protousers.GetUserByEmailRequest\x1a\x18.protousers.UserResponse\"\x00\x12O\n\x0eGetUserByToken\x12!.protousers.GetUserByTokenRequest\x1a\x18.protousers.UserResponse\"\x00\x12V\n\x15GetUserByRefreshToken\x12!.protousers.GetUserByTokenRequest\x1a\x18.protousers.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERRESPONSE']._serialized_start=28
  _globals['_USERRESPONSE']._serialized_end=324
  _globals['_GETUSERBYIDREQUEST']._serialized_start=326
  _globals['_GETUSERBYIDREQUEST']._serialized_end=358
  _globals['_GETUSERBYUSERNAMEREQUEST']._serialized_start=360
  _globals['_GETUSERBYUSERNAMEREQUEST']._serialized_end=404
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=406
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=444
  _globals['_GETUSERBYTOKENREQUEST']._serialized_start=446
  _globals['_GETUSERBYTOKENREQUEST']._serialized_end=484
  _globals['_USERS']._serialized_start=487
  _globals['_USERS']._serialized_end=906
# @@protoc_insertion_point(module_scope)
