"""added_user_avatars

Revision ID: d8bcbf167e0f
Revises: 53bb10f3d0f6
Create Date: 2024-02-22 18:57:03.072364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bcbf167e0f'
down_revision = '53bb10f3d0f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('converted_url', sa.String(), nullable=True),
    sa.Column('converted_filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users_avatars', ['avatar_id'], ['id'])
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.drop_table('users_avatars')
    # ### end Alembic commands ###
