"""Removed activities field for user

Revision ID: e81f9efa794b
Revises: 3c822a812bba
Create Date: 2024-05-01 11:47:10.330040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81f9efa794b'
down_revision = '3c822a812bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
