name: CI/CD Stage

on:
  push:
    branches: [ "dev", "development" ]
  pull_request:
    branches: [ "dev", "development" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build linting containers
      run: docker build -t chack-check-users-lint -f docker/Dockerfile.lint .

    - name: Run linting
      run: docker run --rm chack-check-users-lint
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build tests
      run: docker compose -f docker-compose.test.yml build

    - name: Run tests
      run: docker compose -f docker-compose.test.yml run --rm app poetry run pytest
  build:
    needs: [ test, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-users-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-users-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    needs: [ test, lint, build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://master.k8s.chack-check.ru:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: stage
          manifests:
            kubernetes/stage/deployment.yml
            kubernetes/stage/ingress.yml
            kubernetes/stage/service.yml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chack-users-service:${{ github.sha }}
