name: CI/CD Development

on:
  push:
    branches: [ "feat/*", "feature/*", "fix/*", "dev", "development" ]

jobs:
  development:
    uses: chack-check/diffaction-workflows/.github/workflows/development.yml@main
    with:
      service-name: diffaction-users-service
      run-tests-command: poetry run pytest
