name: CI/CD Stage

on:
  push:
    branches: [ "main", "master" ]

jobs:
  staging:
    uses: chack-check/diffaction-workflows/.github/workflows/staging.yml@main
    with:
      service-name: diffaction-users-service
      app-manifests: |
        kubernetes/stage/app/deployment.yml
        kubernetes/stage/app/service.yml
        kubernetes/stage/app/ingress.yml
      run-tests-command: poetry run pytest
      skiptests: true
    secrets:
      KUBERNETES_SECRET: ${{ secrets.KUBERNETES_SECRET }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLIENT_SERVICE_PAT: ${{ secrets.CLIENT_SERVICE_PAT }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
